arr = input().split()
a =int(arr[0])
b =int(arr[1])
print(1 if a>=b else 0 )
print(1 if a>b else 0)
print(1 if b>=a else 0)
print(1 if b>a else 0)
print(1 if a==b else 0)
print(1 if a!=b else 0)